### ISSUE TITLE
Return consistent scalar types in responses

### ISSUE THREAD

**Issue by Brammm** [teamleadercrm/api#23]
@Brammm commented on [Thu Apr 13 2017](https://github.com/teamleadercrm/api-proxy/issues/16)

Responses are not consistent in their scalar types. Floats returned as string, booleans returned as 0|1...

**Comment by mrnnn** [comment]
Additionally, date transformations

**Comment by hannesvdvreken** [comment]
Seems pretty much done. Can add individual transformations later when needed.
