### ISSUE TITLE
Force users to authenticate with oauth

### ISSUE THREAD

**Issue by Brammm** [teamleadercrm/api#34]

**Comment by stivni** [comment]
B : if I do requests without authentication, the errors tells me to set api_group

```
{"errors":[{"status":"failed","reason":"Please set api_group.","code":401}]}
```

It should tell me to use aouth (and maybe even point me to the documentation)

**Comment by stivni** [comment]
But it seems adding api_group and api_secret to it, doesn't log me in, so in that matter, this is done...

**Comment by Brammm** [comment]
@stivni I had suggested this a couple times, but the answer always was "we don't want to add validation to api proxy, let core just handle the validation."
