### ISSUE TITLE
Extra output API v1 endpoint Get Meeting

### ISSUE THREAD

**Issue by nielsvandenbuverie** [teamleadercrm/api#70]
Extra output for API v1 endpoint: https://app.teamleader.eu/api/getMeeting.php

description: description of the meeting

for_id: id of the contact or company

This extra output is very important for a 15K ARR customer (Tremendous, Glow, Biss) in order to finish an integration. We will need tis output also in v2.

**Comment by stivni** [comment]
add to blueprint v1 first

**Comment by fowbi** [comment]
**for_id** is already present under `location_detailed`

```
"location_detailed": {
        "type": "company_location",
        "contact": "",
        "company": 1
    },
```

```
"location_detailed": {
        "type": "contact_location",
        "contact": 1,
        "company": ""
    },
```

**Comment by Jdww** [comment]
@nielsvandenbuverie What's the for_id? The id of the location company/contact or the external contacts attending?

**Comment by nielsvandenbuverie** [comment]
{
  “id”: 68,
  “title”: “test sms”,
  “duration_minutes”: 60,
  “date_timestamp”: 1467304200,
  “date_day”: “30\/06\/2016”,
  “date_hour”: “18:30”,
  “attending_internal”: [
    {
      “user_id”: 1,
      “name”: “Mathias De Loore”,
      “gsm”: “”,
      “telephone”: “+32 487 89 56 11”,
      “email”: “mathias@rgbscape.be”
    }
  ],
  “attending_external”: [
    {
      “contact_id”: 1138640,
      “name”: “Lowie Gsm”,
      “gsm”: “+32 497 64 61 66”,
      “telephone”: “+32 497 64 61 66”,
      “email”: “lowiebenoot@gmail.com”
    }
  ],
  “creator_id”: 1,
  “canceller_id”: “”,
  “location”: “Rgbscape HQ @ Visserij 43P, 9000 Gent, Belgi&euml;“,
  “location_detailed”: {
    “type”: “predefined_location”,
    “contact”: “”,
    “company”: “”
  },
  “project_id”: “”,
  “milestone_id”: “”,
  “date_added”: 1467302629,
  “date_added_formatted”: “30\/06\/2016 18:03",
  “related_sale_id”: -1,
  “custom_fields”: []
}

**Comment by nielsvandenbuverie** [comment]
@Jdww  The id of the location company/contact. According to this test it should be in there.
