### ISSUE TITLE
prefixed id's for customers

### ISSUE THREAD

**Issue by Steerlin** [teamleadercrm/api#95]
revisit when sufficient endpoints are ready to change this

**Comment by stivni** [comment]
we are going to use a customer-id in as much cases as possible:
`contact-1234` and `company-2345`

**Comment by stivni** [comment]
in case we don't want to expose the type inside the id, we can obfuscate it towards the outside (also good for anti-scraping)
it might be important to keep the type available in the code itself

**Comment by stivni** [comment]
we might need a temporary endpoint to convert old ids into new ids etc... to keep integrations BC compatible
